# Generated by Django 3.0.7 on 2020-06-15 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('School', models.CharField(max_length=300)),
                ('date', models.DateField()),
            ],
        ),
    ]
